let array = ["10GB DataSunday",
    "AlwaysON_Lite_Boost_VT",
    "AlwaysON_Turbo_Boost_VT",
    "AlwaysON_UL_Lite VT",
    "AlwaysON_UL_Maxi VT",
    "AlwaysON_UL_Standard VT",
    "AlwaysON_UL_Starter VT",
    "AlwaysON_UL_Streamer VT",
    "AlwaysON_UL_Super VT",
    "AlwaysON_UL_Ultra VT",
    "DATA1.6GBSurfplus",
    "DATA10GBSun",
    "DATA120GBSurfplus",
    "DATA12GBSurfplus",
    "DATA180GBSurfplus",
    "DATA200GB_BUS2",
    "DATA3.2GBSurfplus",
    "DATA30GBSurfplus",
    "DATA45GBSurfplus",
    "DATA50GB_BUS1",
    "DATA50GB_BUS2",
    "DATA5GBSurfplus",
    "DATA65GBSurfplus",
    "DATA65GBSurfplus-R",
    "DATA7GBSurfplus",
    "DATAAlwaysON_Lite",
    "DATAAlwaysON_Maxi",
    "DATAAlwaysON_Standard",
    "DATAAlwaysON_Starter",
    "DATAAlwaysON_Streamer",
    "DATAAlwaysON_Super",
    "DATAAlwaysON_Ultra",
    "DATABolt",
    "DATABolt_Lite",
    "DATARideON",
    "DATARideONLite",
    "DATASME_LITE",
    "DATASME_STANDARD",
    "DATASME_STARTER",
    "DATASME_SUPER",
    "DATASME_ULTRA",
    "DATATDrive_14",
    "DATATDrive_30",
    "DATATDrive_7",
    "DATATaxify30",
    "DATATaxify7",
    "DATAULNitePlan",
    "DATAULPlan",
    "DATAULTV",
    "DATAUnlimited30days",
    "DATAUnlimitedNight",
    "RideON_Lite_VT",
    "RideON_VT",
    "Taxify_Lite_VT",
    "Taxify_VT",
    "UL_Lite_Boost_VT",
    "UL_Turbo_Boost_VT",
    "UnlimitedDayNightPlan",
    "UnlimitedDayNightPlanPC",
    "UnlimitedNightPlan",
    "UnlimitedNightPlanPC"];

for (const string of array) {
    process.stdout.write(`VOUCHER_TYPE=${string}|`)

}
